project:
  type: book
  # preview settings
  preview: 
    port: 3456
    browser: true
    watch-inputs: true
    navigate: true
    timeout: 3600

book:
  title: "Python Live Book"
  author: "Chaance Graves"
  date: "8/4/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

# format for content rendering
format: live-html
pyodide:
  packages:
    - pandas
    - matplotlib
    - numpy

# backend engine for code execution
engine: jupyter
editor: visual

theme:
  light: cosmo
  dark: darkly

pdf:
  documentclass: scrreprt



